server:
  persistentVolume:
    enabled: false
  scrape_configs:
    - job_name: "team-b-pods"
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - team-b

alertmanager:
  enabled: true
  persistence:
    enabled: false

prometheus-node-exporter:
  enabled: false

namespaceOverride: monitoring-team-b




# command
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prom-team-b prometheus-community/prometheus \
  -n monitoring-team-b \
  -f prom-team-b-values.yaml


# verify
kubectl get pods -n monitoring-team-a  
