# Download IAM Policy
curl -O https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json


# Create IAM Policy

  aws iam create-policy \
  --policy-name AWSLoadBalancerControllerIAMPolicy \
  --policy-document file://iam_policy.json


# Create Service Account (IRSA)
eksctl create iamserviceaccount \
  --cluster task-4 \
  --region ap-south-1 \
  --namespace kube-system \
  --name aws-load-balancer-controller \
  --attach-policy-arn arn:aws:iam::075285241029:policy/AWSLoadBalancerControllerIAMPolicy \
  --approve
  --override-existing-serviceaccounts


# Install ALB Controller

helm repo add eks https://aws.github.io/eks-charts
helm repo update

helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
  -n kube-system \
  --set clusterName=task-4 \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller


  

  aws ec2 create-subnet \
  --vpc-id vpc-05df1ae8560da84b1 \
  --cidr-block 100.64.1.0/24 \
  --availability-zone ap-south-1a

  aws ec2 describe-nat-gateways \
  --filter Name=vpc-id,Values=vpc-05df1ae8560da84b1 \
  --region ap-south-1 \
  --query "NatGateways[].NatGatewayId" \
  --output text

nat-0c22d49cd8bd56a5a

aws ec2 describe-route-tables \
  --filters Name=vpc-id,Values=nat-0c22d49cd8bd56a5a \
  --region ap-south-1

  aws ec2 create-route \
  --route-table-id rtb-03301d054b170fd80 \
  --destination-cidr-block 0.0.0.0/0 \
  --nat-gateway-id nat-0c22d49cd8bd56a5a

  aws ec2 associate-route-table \
  --subnet-id subnet-0b3f696da2659653b \
  --route-table-id rtb-0c1d0e7cb5c06332c

  aws ec2 describe-subnets \
  --filters \
    Name=vpc-id,Values=vpc-05df1ae8560da84b1 \
    Name=availability-zone,Values=ap-south-1b \
  --query "Subnets[].{SubnetId:SubnetId,CIDR:CidrBlock}" \
  --output table

  aws ec2 create-subnet \
  --vpc-id vpc-05df1ae8560da84b1 \
  --cidr-block 100.64.2.0/24 \
  --availability-zone ap-south-1b


 
 
